### ISSUE TITLE
undefined symbol: LAPACKE_dgesv

### ISSUE THREAD

**Issue by silastittes** [jade-cheng/ohana#1]
I read about this software in biorxiv preprint. Thanks for making it available for public use! I'm excited to try it out, but am having some troubles.

I was able to compile `OpenBLAS-0.2.19` without apparent error.

After running  `sudo make install` in the OpenBLas directory,  /opt/OpenBLAS/ appears available. 

I was also able to compile `ohana` without apparent error. Further, I converted my beagle genotype likelihood file to a .lgm file without error. No obvious problems with the file.

However, when I run qpas with the following command:

`ohana/bin/qpas oldBams.lgm -k 4 -qo oldBams.q.matrix -fo oldBams.f.matrix -mi 1`

This is the output:

`seed: 2813454248`

`iter	duration	log_likelihood	delta-lle`
`0	1.014321	-2.1756061889733102e+07`
`ohana/bin/qpas: symbol lookup error: ohana/bin/qpas: undefined symbol: LAPACKE_dgesv`

The q and f matrix files are not written.

I've tried re-installing to no avail. I've tried looking up similar errors concerning  `OpenBlas` and `lapacke,` but am having trouble deciphering how to fix the issue. 

I'm running on Ubuntu 14.04.4.

Hope I've provided all the relevant information.

Thanks!

**Comment by peterdfields** [comment]
Hi @silastittes,

If you take the build approach described in the README.md you will probably need to update your LD_LIBRARY_PATH variable. Specifically, if you do the following in your shell:

`export LD_LIBRARY_PATH=/opt/OpenBLAS/lib/`

the qpas (and other ohana executables) should run without the error you describe.

**Comment by silastittes** [comment]
@peterdfields, that did it! Thanks!
