### ISSUE TITLE
Error: Template with C linkage

### ISSUE THREAD

**Issue by vb-cscottg** [jade-cheng/ohana#13]
Hello.  I seem to be encountering a compiler error (possibly?) when I attempt to 'make' the Ohana software.  I've downloaded and installed OpenBLAS properly, but cannot seem to get the next steps moving.  If it's at all relevant my version of g++ is 'g++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-6)'.  Thanks!

[ohana]$ cat configure.mk
CXX            = g++
OPENBLAS       = /home/ec2-user/OHANA/opt/OpenBLAS
INSTALL_PREFIX = /home/ec2-user/OHANA/opt/ohana
[ohana]$ make
+ src/convert/jade.main.cpp
In file included from /home/ec2-user/OHANA/opt/OpenBLAS/include/lapack.h:58:0,
                 from /home/ec2-user/OHANA/opt/OpenBLAS/include/lapacke.h:37,
                 from src/lib/jade.system.hpp:33,
                 from src/lib/jade.assert.hpp:10,
                 from src/lib/jade.error.hpp:10,
                 from src/lib/jade.args.hpp:10,
                 from src/convert/jade.main.cpp:7:
/usr/include/c++/7/complex:63:3: error: template with C linkage
   template<typename _Tp> class complex;
   ^~~~~~~~
/usr/include/c++/7/complex:64:3: error: template specialization with C linkage
   template<> class complex<float>;
   ^~~~~~~~
/usr/include/c++/7/complex:65:3: error: template specialization with C linkage
   template<> class complex<double>;

**Comment by secastel** [comment]
This issue seems to be related to OpenBLAS 0.3.8. Building Ohana with OpenBLAS 0.3.7 (available [here](https://github.com/xianyi/OpenBLAS/archive/v0.3.7.tar.gz)) solves the problem.
