### ISSUE TITLE
convert crashing

### ISSUE THREAD

**Issue by yassineS** [jade-cheng/ohana#5]
Hi Jade,

I keep running into an issue with convert. I am trying to convert a likelihood file in beagle format into lgm format without luck. The file contains 70-odd samples. I keep getting the following error:

```
convert bgl2lgm input.bgl output.lgm
std::bad_alloc
```

Note that I'm running this on a machine with 32 cores and 240GB of ram, so I don't think it's a memory issue as there's more memory available than the uncompressed data file size.

Thanks,
Yassine

**Comment by jade-cheng** [comment]
Hi Yassine, does the input file `input.bgl` follow the format below?  The names on the header line do not matter.  Just to be sure, could you try it on a small slice of your exact data?

```
marker allelel1 allelel2 Ind0     Ind0     Ind0     Ind1     Ind1     Ind1    
0      0        0        0.000133 0.333287 0.666580 0.333333 0.333333 0.333333
1      0        0        0.000001 0.998406 0.001593 0.333333 0.333333 0.333333
2      0        0        0.000053 0.999946 0.000001 0.333333 0.333333 0.333333
```

**Comment by yassineS** [comment]
Hi Jade, the input.gl is the same format as described (see below):

```
cat input.bgl | cut -f1-9
marker	allele1	allele2	Ind0	Ind0	Ind0	Ind1	Ind1	Ind1
1_14930	0	2	0.333333	0.333333	0.333333	0.005268	0.331576	0.663157
1_14933	2	0	0.333333	0.333333	0.333333	0.666633	0.333314	0.000053
1_17462	2	0	0.333333	0.333333	0.333333	0.666633	0.333314	0.000053
1_20131	2	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_51914	3	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_51935	1	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_51954	2	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_54652	0	1	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_54669	1	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
```

I'm wondering what's going on.

Yassine

**Comment by jade-cheng** [comment]
This snippet of data seems to work fine for me (copied below).  Could you give it a try?

```
$ cat input.bgl 
marker	allele1	allele2	Ind0	Ind0	Ind0	Ind1	Ind1	Ind1
1_14930	0	2	0.333333	0.333333	0.333333	0.005268	0.331576	0.663157
1_14933	2	0	0.333333	0.333333	0.333333	0.666633	0.333314	0.000053
1_17462	2	0	0.333333	0.333333	0.333333	0.666633	0.333314	0.000053
1_20131	2	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_51914	3	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_51935	1	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_51954	2	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_54652	0	1	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
1_54669	1	0	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333

$ convert bgl2lgm input.bgl output.lgm

$ cat output.lgm 
2 9
0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
0.005268	0.666633	0.666633	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333

2 9
0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
0.331576	0.333314	0.333314	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333

2 9
0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
0.663157	5.3e-05	5.3e-05	0.333333	0.333333	0.333333	0.333333	0.333333	0.333333
```

**Comment by yassineS** [comment]
Hi Jade,

It works fine for the snippet but not the full dataset. That’s my issue, it crashes complaining about memory hence: `std::bad_alloc`.

Y

**Comment by jade-cheng** [comment]
Data size shouldn't be an issue as long as enough ram is enough, which is your case.  I did a quick check.  I see that I've executed this command on a dataset of size 96G containing 201 samples and 18,947,088 markers.

**Comment by yassineS** [comment]
It appears to be the case, the file is 120G with 65 samples and 20M markers. Breaking the file by chromosome fixed the issue. This is particularly still puzzling because I have 265G of ram with nothing else running.

Anyways splitting by chromosome fixed the issue. Many thanks!

Yassine
